general {
    lock_cmd = pidof swaylock || swaylock -f -c 000000
    before_sleep_cmd = loginctl lock-session
}

# Lock screen after 5 minutes of idle
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn off both displays after 5 minutes of being locked (10 minutes total idle)
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
