# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input

input {
    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2
    sensitivity = 0

    # Keyboard repeat settings
    repeat_rate = 50    # keys per second (default: 25)
    repeat_delay = 300  # ms before repeat starts (default: 600)
}
